<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default.entrypoints' => 0,

], [

0 => [
    'base' => '/build/',
    'entryPoints' => [
        'app' => [
            'js' => [
                'http://[::1]:5179/build/frontend/src/main.jsx',
            ],
        ],
    ],
    'legacy' => false,
    'metadatas' => [],
    'version' => [
        '6.4.7',
        6,
        4,
        7,
    ],
    'viteServer' => 'http://[::1]:5179',
],

]];
